name: feature_pipeline

on:
  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:  # Add this for manual triggering

jobs:
  feature-pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: poetry install
      if: steps.cache.outputs.cache-hit != 'true'
      
    - name: Run feature generation script
      env: 
        HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      run: make features

