name: inference-pipeline

on:
  schedule:
    - cron: '30 * * * *'

  workflow_dispatch:  # Add this for manual triggering

jobs:
  inference-pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: poetry install
      if: steps.cache.outputs.cache-hit != 'true'
      
    - name: Generating new batch of predictions
      env: 
        HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        COMET_ML_API_KEY: ${{ secrets.COMET_ML_API_KEY }}
        COMET_ML_WORKSPACE: ${{ secrets.COMET_ML_WORKSPACE }}
        COMET_ML_PROJECT_NAME: ${{ secrets.COMET_ML_PROJECT_NAME }}
      run: make inference
